/**
 * packages/token-engine/index.ts
 *
 * Generates 100% self-contained, flat Solidity ERC-20 contracts.
 * NO external imports. NO abstract bases. NO multiple inheritance chains.
 * All logic inlined. Compiles cleanly with solc ^0.8.20.
 */

export interface TokenConfig {
  name: string;
  symbol: string;
  decimals: number;
  initialSupply: string;
  isMintable: boolean;
  isBurnable: boolean;
  isPausable: boolean;
  hasTax: boolean;
  taxBps: number;
  taxRecipient: string;
  maxSupply?: string;
  isGovernance: boolean;
}

export function generateTokenSource(config: TokenConfig): string {
  const { name, symbol, decimals, initialSupply, isMintable, isBurnable, isPausable, hasTax, taxBps, taxRecipient, maxSupply } = config;
  const contractName = (name || 'Token').replace(/[^a-zA-Z0-9_]/g, '').replace(/^[0-9]+/, '') || 'Token';
  const safeRecipient = taxRecipient && /^0x[0-9a-fA-F]{40}$/.test(taxRecipient) ? taxRecipient : '';

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// =================================================================
// ${name} (${symbol})
// Generated by Cronos Studio — self-contained, zero dependencies
// =================================================================

contract ${contractName} {

    // ── Events ───────────────────────────────────────────────────
    event Transfer(address indexed from, address indexed to, uint256 value);
    event Approval(address indexed owner, address indexed spender, uint256 value);
    event OwnershipTransferred(address indexed previousOwner, address indexed newOwner);
    ${isPausable ? `event Paused(address account);\n    event Unpaused(address account);` : ''}

    // ── Storage ──────────────────────────────────────────────────
    string public name = "${name}";
    string public symbol = "${symbol}";
    uint8 public decimals = ${decimals};
    uint256 private _totalSupply;
    address private _owner;
    ${isPausable ? 'bool private _paused;' : ''}
    ${maxSupply ? `uint256 public constant MAX_SUPPLY = ${maxSupply} * (10 ** ${decimals});` : ''}
    ${hasTax ? `uint256 public taxBps = ${taxBps};\n    address public taxRecipient;` : ''}
    ${hasTax ? 'mapping(address => bool) public isExcludedFromTax;' : ''}

    mapping(address => uint256) private _balances;
    mapping(address => mapping(address => uint256)) private _allowances;

    // ── Constructor ──────────────────────────────────────────────
    constructor() {
        _owner = msg.sender;
        ${hasTax ? `taxRecipient = ${safeRecipient !== '' ? safeRecipient : 'msg.sender'};` : ''}
        ${hasTax ? 'isExcludedFromTax[msg.sender] = true;' : ''}
        _mint(msg.sender, ${initialSupply} * (10 ** ${decimals}));
        emit OwnershipTransferred(address(0), msg.sender);
    }

    // ── Ownership ────────────────────────────────────────────────
    modifier onlyOwner() {
        require(msg.sender == _owner, "Not owner");
        _;
    }
    function owner() public view returns (address) { return _owner; }
    function renounceOwnership() external onlyOwner {
        emit OwnershipTransferred(_owner, address(0));
        _owner = address(0);
    }
    function transferOwnership(address newOwner) external onlyOwner {
        require(newOwner != address(0), "Zero address");
        emit OwnershipTransferred(_owner, newOwner);
        _owner = newOwner;
    }

    ${isPausable ? `
    // ── Pausable ─────────────────────────────────────────────────
    modifier whenNotPaused() { require(!_paused, "Paused"); _; }
    function paused() public view returns (bool) { return _paused; }
    function pause() external onlyOwner { _paused = true; emit Paused(msg.sender); }
    function unpause() external onlyOwner { _paused = false; emit Unpaused(msg.sender); }
    ` : ''}

    // ── ERC20 ────────────────────────────────────────────────────
    function totalSupply() public view returns (uint256) { return _totalSupply; }
    function balanceOf(address account) public view returns (uint256) { return _balances[account]; }

    function transfer(address to, uint256 amount) public ${isPausable ? 'whenNotPaused ' : ''}returns (bool) {
        _transfer(msg.sender, to, amount);
        return true;
    }
    function allowance(address tokenOwner, address spender) public view returns (uint256) {
        return _allowances[tokenOwner][spender];
    }
    function approve(address spender, uint256 amount) public returns (bool) {
        require(spender != address(0), "Zero address");
        _allowances[msg.sender][spender] = amount;
        emit Approval(msg.sender, spender, amount);
        return true;
    }
    function transferFrom(address from, address to, uint256 amount) public ${isPausable ? 'whenNotPaused ' : ''}returns (bool) {
        uint256 allowed = _allowances[from][msg.sender];
        if (allowed != type(uint256).max) {
            require(allowed >= amount, "Allowance exceeded");
            _allowances[from][msg.sender] = allowed - amount;
        }
        _transfer(from, to, amount);
        return true;
    }
    function increaseAllowance(address spender, uint256 addedValue) external returns (bool) {
        _allowances[msg.sender][spender] += addedValue;
        emit Approval(msg.sender, spender, _allowances[msg.sender][spender]);
        return true;
    }
    function decreaseAllowance(address spender, uint256 subtractedValue) external returns (bool) {
        uint256 current = _allowances[msg.sender][spender];
        require(current >= subtractedValue, "Below zero");
        _allowances[msg.sender][spender] = current - subtractedValue;
        emit Approval(msg.sender, spender, _allowances[msg.sender][spender]);
        return true;
    }

    function _transfer(address from, address to, uint256 amount) internal {
        require(from != address(0) && to != address(0), "Zero address");
        require(_balances[from] >= amount, "Insufficient balance");
        ${hasTax ? `
        if (taxBps > 0 && taxRecipient != address(0) && !isExcludedFromTax[from] && !isExcludedFromTax[to]) {
            uint256 tax = (amount * taxBps) / 10000;
            _balances[from] -= amount;
            _balances[taxRecipient] += tax;
            _balances[to] += (amount - tax);
            emit Transfer(from, taxRecipient, tax);
            emit Transfer(from, to, amount - tax);
        } else {
            _balances[from] -= amount;
            _balances[to] += amount;
            emit Transfer(from, to, amount);
        }` : `
        _balances[from] -= amount;
        _balances[to] += amount;
        emit Transfer(from, to, amount);`}
    }
    function _mint(address account, uint256 amount) internal {
        require(account != address(0), "Zero address");
        _totalSupply += amount;
        _balances[account] += amount;
        emit Transfer(address(0), account, amount);
    }
    function _burn(address account, uint256 amount) internal {
        require(_balances[account] >= amount, "Burn exceeds balance");
        _balances[account] -= amount;
        _totalSupply -= amount;
        emit Transfer(account, address(0), amount);
    }

    ${isMintable ? `
    // ── Mint ──────────────────────────────────────────────────────
    function mint(address to, uint256 amount) external onlyOwner {
        ${maxSupply ? `require(_totalSupply + amount <= MAX_SUPPLY, "Exceeds max supply");` : ''}
        _mint(to, amount);
    }` : ''}

    ${isBurnable ? `
    // ── Burn ──────────────────────────────────────────────────────
    function burn(uint256 amount) external { _burn(msg.sender, amount); }
    function burnFrom(address account, uint256 amount) external {
        uint256 allowed = _allowances[account][msg.sender];
        require(allowed >= amount, "Allowance exceeded");
        if (allowed != type(uint256).max) _allowances[account][msg.sender] = allowed - amount;
        _burn(account, amount);
    }` : ''}

    ${hasTax ? `
    // ── Tax ───────────────────────────────────────────────────────
    function setTaxBps(uint256 _bps) external onlyOwner { require(_bps <= 1000, "Max 10%"); taxBps = _bps; }
    function setTaxRecipient(address _recipient) external onlyOwner { require(_recipient != address(0), "Zero addr"); taxRecipient = _recipient; }
    function setExcludedFromTax(address account, bool excluded) external onlyOwner { isExcludedFromTax[account] = excluded; }` : ''}

    // ── Recover accidentally sent tokens ─────────────────────────
    function rescueTokens(address token, address to, uint256 amount) external onlyOwner {
        require(token != address(this), "Cannot rescue self");
        (bool ok,) = token.call(abi.encodeWithSignature("transfer(address,uint256)", to, amount));
        require(ok, "Transfer failed");
    }
}
`;
}

export function validateTokenConfig(config: Partial<TokenConfig>): string[] {
  const errors: string[] = [];
  if (!config.name?.trim()) errors.push('Token name is required');
  if (!config.symbol?.trim()) errors.push('Token symbol is required');
  if (config.symbol && (config.symbol.length < 2 || config.symbol.length > 8)) errors.push('Symbol must be 2-8 characters');
  if (!config.initialSupply || isNaN(Number(config.initialSupply)) || Number(config.initialSupply) <= 0) errors.push('Initial supply must be a positive number');
  if (config.hasTax && (config.taxBps ?? 0) > 1000) errors.push('Tax must be <= 10% (1000 bps)');
  if (config.decimals !== undefined && (config.decimals < 0 || config.decimals > 18)) errors.push('Decimals must be 0-18');
  return errors;
}

export const DEFAULT_TOKEN_CONFIG: TokenConfig = {
  name: '', symbol: '', decimals: 18, initialSupply: '1000000',
  isMintable: false, isBurnable: false, isPausable: false,
  hasTax: false, taxBps: 0, taxRecipient: '', isGovernance: false,
};

export interface TokenTemplate {
  id: string; name: string; description: string; config: Partial<TokenConfig>;
}

export const TOKEN_TEMPLATES: TokenTemplate[] = [
  { id: 'basic',    name: 'Basic Token',    description: 'Fixed supply — clean and simple',        config: {} },
  { id: 'utility',  name: 'Utility Token',  description: 'Mintable + burnable + pausable',          config: { isMintable: true, isBurnable: true, isPausable: true } },
  { id: 'defla',    name: 'Deflationary',   description: 'Holders can burn to reduce supply',       config: { isBurnable: true } },
  { id: 'tax',      name: 'Tax Token',      description: 'Auto transfer tax → treasury',            config: { hasTax: true, taxBps: 300, isBurnable: true } },
];
